package GUI;

import java.util.ArrayList;
import Clases.Contactos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kenny Londoño
 */
public class Principal extends javax.swing.JFrame {
ArrayList Agenda = new ArrayList();
    /**
     * Creates new form Agenda
     */
    public Principal() {
        initComponents();
        Crear_Modelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVerAgenda = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTContactos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAgendaPersonal = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtIdentificacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerAgenda.setBackground(new java.awt.Color(153, 153, 153));
        btnVerAgenda.setForeground(new java.awt.Color(0, 0, 0));
        btnVerAgenda.setText("Ver Datos");
        btnVerAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAgendaActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 140, -1));

        btnLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(153, 153, 153));
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jTContactos.setBackground(new java.awt.Color(153, 153, 153));
        jTContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTContactos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 390, 270));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Identificacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombres");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellidos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Direccion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtAgendaPersonal.setBackground(new java.awt.Color(255, 255, 255));
        txtAgendaPersonal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtAgendaPersonal.setForeground(new java.awt.Color(255, 255, 255));
        txtAgendaPersonal.setText("Agenda Personal");
        jPanel1.add(txtAgendaPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        txtNombres.setBackground(new java.awt.Color(153, 153, 153));
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 160, -1));

        txtApellidos.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 160, -1));

        txtTelefono.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 160, -1));

        txtDireccion.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 160, -1));

        txtIdentificacion.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
     String id=txtIdentificacion.getText();
     String nom=txtNombres.getText();
     String ape=txtApellidos.getText();
     String tel=txtTelefono.getText();
     String dir=txtDireccion.getText();
     if(!id.isEmpty()){
         if(!nom.isEmpty()){
             if(!ape.isEmpty()){
                 if(!tel.isEmpty()){
                     if(!dir.isEmpty()){
                         Contactos nuevo_contacto = new Contactos();
                         nuevo_contacto.setIdentificacion(Integer.parseInt(id));                       
                         nuevo_contacto.setNombres(nom);
                         nuevo_contacto.setApellidos(ape);
                         nuevo_contacto.setTelefono(tel);
                         nuevo_contacto.setDireccion(dir);
                         Agenda.add(nuevo_contacto);
                         JOptionPane.showMessageDialog(null, "¡el contacto fue guardado con exito!");
         
                     } else{
                         JOptionPane.showMessageDialog(null,"Ingrese la Direccion");                   
                     }
                 
                 }    else {
                     JOptionPane.showMessageDialog(null,"Ingrese el telefono");
                 }         
             } else{
                 JOptionPane.showMessageDialog(null,"Ingrese los apellidos");
             }
         
         } else{
             JOptionPane.showMessageDialog(null, "Ingrese los nombres");
         }
     } else{
         JOptionPane.showMessageDialog(null,"Ingrese la identificacion");
     }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
 txtIdentificacion.setText(" ");
 txtNombres.setText(" ");
txtApellidos.setText(" ");
txtTelefono.setText(" ");
txtDireccion.setText(" ");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVerAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAgendaActionPerformed
        Object O[]=null;
        for (int i = 0; i< Agenda.size(); i++) {
            Contactos con = (Contactos) Agenda.get(i);
            modelo.addRow(O);
            modelo.setValueAt(con.getIdentificacion(), i, 0);
            modelo.setValueAt(con.getNombres(), i, 1);
            modelo.setValueAt(con.getApellidos(),i, 2);
            modelo.setValueAt(con.getTelefono(),i,3);
            modelo.setValueAt(con.getDireccion(), i,4);        
        }
    }//GEN-LAST:event_btnVerAgendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    DefaultTableModel modelo;
    private void Crear_Modelo() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "Identificacion", "Nombres", "Apellidos", "Telefono", "Direccion"}) {
                            Class [] types =new Class[]{
                                java.lang.String.class, java.lang.String.class,
                                java.lang.String.class, java.lang.String.class,  java.lang.String.class 
};
boolean[] canEdit= new boolean[]{
    false, false, false, false, false
};

public Class getColumnClass (int columnIndex) {
    return types [columnIndex];
}
 
public boolean isCellEditable (int rowIndex, int colIndex) {
return canEdit[colIndex];
            }
});
    jTContactos.setModel(modelo);
}
catch (Exception e) {
JOptionPane.showMessageDialog(null, e.toString()+"error2" );
                        }}

                            
                            
                            
                            
                    
        
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVerAgenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTContactos;
    private javax.swing.JLabel txtAgendaPersonal;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
